#quarkus.log.level=DEBUG
#quarkus.log.category."io.quarkus.cache".level=DEBUG
mp.jwt.verify.publickey.location=http://localhost:8081/publicKey.pem
mp.jwt.verify.issuer=globant
quarkus.smallrye-jwt.enabled=true

quarkus.datasource.db-kind=mysql
quarkus.datasource.reactive.url=vertx-reactive:mysql://localhost:3307/db_rates
quarkus.datasource.username=root
quarkus.datasource.password=1a.2b.3c.

# Configurar el tipo de base de datos que se está utilizando
quarkus.datasource.reactive.jdbc.url=jdbc:mysql://localhost:3307/db_rates
quarkus.datasource.reactive.jdbc.driver=com.mysql.cj.jdbc.Driver

# Configuración para Hibernate ORM
quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=true
quarkus.datasource.reactive=true

# Opciones de conexión
quarkus.datasource.jdbc.max-size=8

quarkus.cache.enabled=true
quarkus.cache.caffeine.currency-cache.expire-after-write=5M
quarkus.cache.caffeine.currency-cache.initial-capacity=100
quarkus.cache.caffeine.currency-cache.maximum-size=1000
