#quarkus.log.level=DEBUG
#quarkus.log.category."io.quarkus.cache".level=DEBUG

quarkus.cache.enabled=true
quarkus.cache.caffeine.currency-cache.expire-after-write=5M
quarkus.cache.caffeine.currency-cache.initial-capacity=100
quarkus.cache.caffeine.currency-cache.maximum-size=1000
